set(PROJECT_VERSION "1.0.3")
set(PROJECT_YEAR "2026")
set(PROJECT_RELEASE_DATE "2026-02-08")
set(PROJECT_PACKAGE_NAME "range-family")
set(PROJECT_TARGET_NAME "family")
set(PROJECT_HUMAN_NAME "Range Family")
set(PROJECT_SHORT_NAME "Family")
set(PROJECT_FAMILY_NAME "Range Software")
set(PROJECT_TITLE "Family")
set(PROJECT_DESCRIPTION "Range Family tool")
set(PROJECT_AUTHOR "Tomáš Šoltys")
set(PROJECT_AUTHOR_ADDRESS "Ke Zlatkovu 597, 25070 Odolena Voda, Czech Republic")
set(PROJECT_EMAIL "tomas.soltys@range-software.com")
set(PROJECT_WWW "https://www.range-software.com")
set(PROJECT_WWW_DOMAIN "range-software.com")
